from distutils.core import setup
setup(name='pysmssend',
    version='1.39',
    description='Send SMS over the Internet',
    author='Markos Chandras',
    author_email='hwoarang_gr@users.sourceforge.net',
    license='GPLv3',
    url='http://pysmssend.sourceforge.net',
    py_modules=['pysmssendmod/__init__',
'pysmssendmod/about',
'pysmssendmod/addressfunc',
'pysmssendmod/pysmssendgui',
'pysmssendmod/accountmanager',
'pysmssendmod/tray',
'pysmssendmod/updater',
'pysmssendmod/updater2',
'pysmssendmod/myloadaccount',
'pysmssendmod/checklength',
'pysmssendmod/myinserts',
'pysmssendmod/mydeleteaccount',
'pysmssendmod/mydeletefile',
'pysmssendmod/mystoreaccount',
'pysmssendmod/myallowsend',
'pysmssendmod/creditsleft',
'pysmssendmod/login',
'pysmssendmod/mysmssend',
'pysmssendmod/usage',
'pysmssendmod/cmdfunc'])
